### ISSUE TITLE
Incorrect word detection

### ISSUE THREAD

**Issue by andrey-helldar** [ConsoleTVs/Profanity#22]
| Package | Version |
|:---|:---|
| `consoletvs/profanity` | `3.1.0` |

I write:
> who i am here

I get:

> who i ** here

![image](https://user-images.githubusercontent.com/10347617/142033938-5568ee49-0e9a-44cb-994a-f4daa114efdb.png)

**Comment by sebastianheise** [comment]
The word `am` (unfortunately) is in the dictionary for language `tr`. 
By not being able to select a specific language when checking, it would mark any string containing a `I am` as profane, which makes it pretty much unusable for the English language :( 
I would propose to remove this word - or add an option to specify the language you want to filter.
I have solved this by making my own copy of the dictionary and removing it.
