### ISSUE TITLE
Whole word matching option

### ISSUE THREAD

**Issue by osappuk** [ConsoleTVs/Profanity#3]
Hi,

Thank you for sharing the code. Is it possible to have whole word only matching option? For example, in my string there is a word "circumstances" and it is picked out by badWords() as "cum" :-( Thanks!

**Comment by osappuk** [comment]
It is really useless when a dictionary contain the word "ass" then the badWords() function picking out everything like: assess, classmates, assignment, etc.

Am I missing the usage of a flag to only filter whole word or is this package did not seriously consider this option? Please help, thanks!

**Comment by ConsoleTVs** [comment]
Done in 2.0.0

as ->strict(true/false) and ->strictClean(true/false). Both documented on the main page. Cheers!

**Comment by osappuk** [comment]
Super, thank you!

**Comment by osappuk** [comment]
I am not sure what is wrong but I carefully test V2.0.0 but the badWords() function return empty array while there are definitely bad words :( Could you have a look, please. Thanks!

**Comment by ConsoleTVs** [comment]
![image](https://user-images.githubusercontent.com/6124435/33568896-31f559d0-d928-11e7-8ed8-9cd3b0ebc3a3.png)

![image](https://user-images.githubusercontent.com/6124435/33568882-2a3d09f4-d928-11e7-90b2-32023788c0f6.png)

Seems to be working for me :o

**Comment by osappuk** [comment]
Ah, I know why. It is because we did not convert strings to lowercase before comparison in here: **in_array($value['word'], $words)** . Could you please fix that? Thank you!

**Comment by ConsoleTVs** [comment]
Fixed
